[add] 商品一覧と商品登録機能追加
EC-site-TeamSmile/nagano_cake pull request #12
Opened 2021-05-17 10:52 UTC by hikaru-webcamp

商品一覧と商品登録機能追加を実施しました。
確認お願いします。

画像
![商品一覧](https://user-images.githubusercontent.com/79980351/118477096-48fd7d80-b749-11eb-94c7-37c476649ca9.png)
![商品登録](https://user-images.githubusercontent.com/79980351/118477099-4a2eaa80-b749-11eb-8220-08294ff4603c.png)

2021-05-17 11:26 UTC, snaruse389 requested changes
少し細かいかもしれませんが、確認の方よろしくお願いします

2021-05-17 11:26 UTC, snaruse389 commented on app/views/admin/products/index.html.erb
> +            <td><%= link_to product.name, admin_product_path(product.id) %></td>
```suggestion
            <td><%= link_to product.name, admin_product_path(product) %></td>
```
productが商品データなのでわざわざidを指定しなくても、その商品へのリンクになると思います。

2021-05-17 11:26 UTC, snaruse389 commented on app/views/admin/products/index.html.erb
> +            <td><%= products.is_active %></td>
商品のステータスの表記がこのままだとtrue,falseになりませんか？
販売中、販売中止中と表示したほうがよくないですか？

例えば、productモデルファイルに
enum is_active: {販売中: true, 販売中止: false}
追加すればなると思います。

2021-05-17 12:35 UTC, Seiryu-alt requested changes
修正点出しておきました
確認お願いします！

2021-05-17 12:35 UTC, Seiryu-alt commented on app/views/admin/products/index.html.erb
> +            <td><%= products.price %></td>
`products`ではなく、`pruduct`です。
商品ジャンルのカラムが抜けているのでこの後に追加しましょう。
```suggestion
            <td><%= product.price %></td>
            <td><%= product.genre.name %></td>
```

2021-05-17 12:35 UTC, Seiryu-alt commented on app/views/admin/products/index.html.erb
> +            <td><%= products.is_active %></td>
こちらも同様に`product`です。
if文を用いて`is_active`カラムの値によって表示内容を切り替えましょう。
```suggestion
            <td>
              <% if product.is_active %>
                <span class="text-success">販売中</span>
              <% else %>
                <span class="text-secondary">販売停止中</span>
              <% end %>
            </td>
```

2021-05-17 13:53 UTC, hikaru-webcamp commented on app/views/admin/products/index.html.erb
> +            <td><%= link_to product.name, admin_product_path(product.id) %></td>
確認ありがとうございます。
はい。おっしゃるとおりですが、リーダブルコード的にidをつけたほうが丁寧とメンターさんに教わりました。

2021-05-17 13:53 UTC, hikaru-webcamp commented on app/views/admin/products/index.html.erb
> +            <td><%= products.is_active %></td>
ありがとうございます。りゅうぽんが下で書いてくれたif文で対応します

2021-05-17 13:53 UTC, hikaru-webcamp commented on app/views/admin/products/index.html.erb
> +            <td><%= products.is_active %></td>
ありがとうございます。修正致します

2021-05-17 14:39 UTC, Seiryu-alt approved these changes
OKです
お疲れさまでした！

2021-05-18 00:42 UTC, snaruse389 approved these changes
確認しました

2021-05-18 00:42 UTC, merged