[add]public商品一覧画面・機能
EC-site-TeamSmile/nagano_cake pull request #14
Opened 2021-05-17 11:44 UTC by haaanyan

#index.html編集
#products controller へ商品一覧表示のための記述
#attachment_imageは別途、商品登録機能merge後確認します。

2021-05-17 13:15 UTC, snaruse389 requested changes
確認よろしくお願いします。

2021-05-17 13:15 UTC, snaruse389 commented on app/views/public/products/index.html.erb
> +             <p class="card-text">¥<%= product.tax_price %></p>
```suggestion
             <p class="card-text">¥<%= product.tax_price.to_s(:delimited) %></p>
```
これを付けると３桁ごとに , に点を表示できます

2021-05-17 13:15 UTC, snaruse389 commented on app/views/public/products/index.html.erb
> +        <h3>商品一覧<span class="small">(全<%= Product.where(is_active: true).count %>件)</span></h3>
```suggestion
        <h3>商品一覧<span class="small">(全<%= @products_active.count %>件)</span></h3>
```
productsコントローラー
@products_active = Product.where(is_active: true)
@products = @products_active..page(params[:page]).per(8)

とかはどうですか？

2021-05-17 14:04 UTC, Seiryu-alt requested changes
修正点出しておきました
確認お願いします

2021-05-17 14:04 UTC, Seiryu-alt commented on app/views/public/products/index.html.erb
> +            <%= attachment_image_tag(product, :image, size: "200x200")
`%>`が抜けています
```suggestion
            <%= attachment_image_tag(product, :image, size: "200x200") %>
```

2021-05-17 14:04 UTC, Seiryu-alt commented on app/views/public/products/index.html.erb
> +        <h3>商品一覧<span class="small">(全<%= Product.where(is_active: true).count %>件)</span></h3>
kaminariを使うのであれば、全件数を取得する`total_count`メソッドが用意されてます。
参考：http://nekorails.hatenablog.com/entry/2018/10/15/005146#total_count-%E5%85%A8%E4%BD%93%E3%81%AE%E3%83%AC%E3%82%B3%E3%83%BC%E3%83%89%E6%95%B0
```suggestion
        <h3>商品一覧<span class="small">(全<%= @products.total_count %>件)</span></h3>
```

2021-05-18 02:10 UTC, haaanyan commented on app/views/public/products/index.html.erb
> +             <p class="card-text">¥<%= product.tax_price %></p>
上記、修正いたしました。

2021-05-18 02:11 UTC, haaanyan commented on app/views/public/products/index.html.erb
> +        <h3>商品一覧<span class="small">(全<%= Product.where(is_active: true).count %>件)</span></h3>
total_countメソッドにて修正いたしました。

2021-05-18 02:11 UTC, haaanyan commented on app/views/public/products/index.html.erb
> +            <%= attachment_image_tag(product, :image, size: "200x200")
修正いたしました。

2021-05-18 02:17 UTC, Seiryu-alt approved these changes
OKです
お疲れさまでした

2021-05-18 02:34 UTC, snaruse389 approved these changes
確認しました。

2021-05-18 02:34 UTC, merged