[add] ジャンル一覧と編集ページの追加
EC-site-TeamSmile/nagano_cake pull request #22
Opened 2021-05-18 11:13 UTC by hikaru-webcamp

管理側のジャンル一覧と編集ページを作成しました。
＜その他細かいところもやりました＞
・りゅうぽんが朝くれた、バリデーションの部分テンプレートを使ってそれぞれのビュー（自分が担当したとこのみ）に反映。
・インデント全角になってたとこなおしました。（特に管理側のTOPページ）

2021-05-18 13:39 UTC, snaruse389 requested changes
細かいところですが、確認よろしくお願いします。

2021-05-18 13:39 UTC, snaruse389 commented on app/views/admin/genres/index.html.erb
> +              <td><%= link_to '編集', edit_admin_genre_path(genre.id), class: 'btn btn-sm btn-success' %></td>
```suggestion
              <td><%= link_to '編集', edit_admin_genre_path(genre), class: 'btn btn-sm btn-success' %></td>
```
genreというデータだけでidを勝手に探してくれます

2021-05-19 00:30 UTC, Seiryu-alt approved these changes
OKです
お疲れさまでした！

2021-05-19 01:38 UTC, snaruse389 approved these changes
確認しました

2021-05-19 01:38 UTC, merged