配送先登録・編集機能
EC-site-TeamSmile/nagano_cake pull request #30
Opened 2021-05-19 07:21 UTC by haaanyan

#　address コントローラーへ登録・編集アクション追記
#    index/edit view 記述

![image](https://user-images.githubusercontent.com/78293400/118772028-36588500-b8be-11eb-850a-c5e346c22ac3.png)

![image](https://user-images.githubusercontent.com/78293400/118772104-4f613600-b8be-11eb-82d7-579a9d2b1e96.png)

2021-05-19 08:36 UTC, hikaru-webcamp approved these changes
機能の対応が終わったらでいいので、配送先登録/一覧 と配送先編集のビューは**一部パーシャル化（部分テンプレート）**できる為、忘れずに。

![image](https://user-images.githubusercontent.com/79980351/118781148-b2a39600-b8c7-11eb-99e2-70f509426fce.png)
![image](https://user-images.githubusercontent.com/79980351/118781180-bb946780-b8c7-11eb-9689-f2aa97a0fafe.png)

部分テンプレートする時に登録ボタンと編集ボタンを変更しないといけない為、
下記で対応できるかと。参考までに。
        <% if address.id.nil? %>
                <%= f.submit "新規登録", class: 'btn btn-success' %>
              <%else%>
                <%= f.submit "変更内容を保存", class: 'btn btn-success' %>
          <% end %>

2021-05-19 09:23 UTC, Seiryu-alt requested changes
確認お願いします。
`address`モデルのカラムにバリデーションの設定を忘れていたため、合わせて追加をお願いしたいです。
`app/models/address.rb`ファイルの2行目の後に以下のバリデーションを設定するコードを追加お願いします。
```
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :address_name, presence: true
```

2021-05-19 09:23 UTC, Seiryu-alt commented on app/controllers/public/addresses_controller.rb
> +      render :index
`render`を使う場合、`index`アクションの処理を通さないので`@addresses`の指定が必要になります。
```suggestion
      @addresses = Address.where(customer: current_customer)
      render :index
```

2021-05-19 09:23 UTC, Seiryu-alt commented on app/controllers/public/addresses_controller.rb
> +    redirect_to addresses_path
更新処理に失敗した場合は再度編集ページを表示するようにしましょう
```suggestion
    if @address.update(address_params)
      redirect_to addresses_path
    else
      render :edit
    end
```

2021-05-19 09:23 UTC, Seiryu-alt commented on app/views/public/addresses/index.html.erb
> +
フォームエラーの部分テンプレート使って頂けると嬉しいです
```suggestion
        <%= render "shared/form_error", model: @address %>
```

2021-05-19 09:23 UTC, Seiryu-alt commented on app/views/public/addresses/edit.html.erb
> +
フォームエラーの部分テンプレート使って頂けると嬉しいです。
```suggestion
        <%= render "shared/form_error", model: @address %>
```

2021-05-19 09:24 UTC, hikaru-webcamp commented on app/views/public/addresses/edit.html.erb
> +        </div>
&lt;/div&gt;
が抜けてます

2021-05-20 02:29 UTC, haaanyan commented on app/views/public/addresses/edit.html.erb
> +
ご指摘5点修正しました。

2021-05-20 02:29 UTC, haaanyan commented on app/views/public/addresses/edit.html.erb
> +        </div>
修正しました。

2021-05-20 02:33 UTC, Seiryu-alt approved these changes
OKです！

2021-05-20 02:33 UTC, merged