Nagano cake readme
EC-site-TeamSmile/nagano_cake pull request #46
Opened 2021-05-20 07:12 UTC by hikaru-webcamp

Readme作成しました。
ロゴも加えオリジナリティを加味しました。
確認お願いします。

2021-05-20 07:49 UTC, haaanyan approved these changes
作成ありがとうございます！

2021-05-20 09:22 UTC, snaruse389 requested changes
確認よろしくお願いします。

2021-05-20 09:22 UTC, snaruse389 commented on README.md
> +そういった店主の強い思いから、通販サイトを開設することになりました。
要件定義書の案件の背景
「元々近隣住民が顧客だったが、昨年始めたInstagramから人気となり、全国から注文が来る ようになった。 InstagramのDMやメールで通販の注文を受けていたが、情報管理が煩雑になってきたため、 管理機能を含んだ通販サイトを開設しようと思い至った。」

これで大丈夫なのではないか？

2021-05-20 09:22 UTC, snaruse389 commented on README.md
> +* ステータス：注文・製作状況について管理するための値。「注文ステータス」 と「製作ステータス」の2種類がある。
販売ステータス、会員ステータス、ジャンル、注文個数、商品小計も書いておくべきではないのか？

2021-05-20 09:22 UTC, snaruse389 commented on README.md
> +  * 製作ステータス(製作待ち/製作中/製作完了)
```suggestion
  * 注文ステータス(入金待ち/入金済み/製作中/発送準備中/発送済み)
  * 製作ステータス(着手不可/製作待ち/製作中/製作完了)
```

2021-05-20 12:50 UTC, Seiryu-alt approved these changes
お疲れさまです
ロゴ良いですね👍

2021-05-21 00:47 UTC, snaruse389 approved these changes
確認しました。

2021-05-21 00:47 UTC, merged