[fix] 商品登録・編集画面、商品詳細画面のレイアウトを調整しました
EC-site-TeamSmile/nagano_cake pull request #49
Opened 2021-05-20 09:07 UTC by Seiryu-alt

![image](https://user-images.githubusercontent.com/80801851/118951529-201df800-b996-11eb-93d0-8134581aa9f6.png)
![image](https://user-images.githubusercontent.com/80801851/118951620-3330c800-b996-11eb-9c12-0a87e4b64e20.png)

2021-05-20 10:33 UTC, snaruse389 requested changes
ヘッターとページの名前のスペースが全体的に狭いと感じました。
広げてみてはどうでしょうか？

2021-05-20 12:58 UTC, Seiryu-alt commented
> ヘッターとページの名前のスペースが全体的に狭いと感じました。
> 広げてみてはどうでしょうか？

ヘッダーとページタイトルの間のマージンは、`application.html.erb`に記述して全ページで統一した方が良いと思ったのですがどうでしょう？
`application.html.erb`で書くつもりだったので、管理者側では個別のページにはヘッダーとタイトルの間にマージンを設定していません。

2021-05-20 23:19 UTC, hikaru-webcamp approved these changes
承認します

2021-05-21 00:53 UTC, snaruse389 commented
> > ヘッターとページの名前のスペースが全体的に狭いと感じました。
> > 広げてみてはどうでしょうか？
> 
> ヘッダーとページタイトルの間のマージンは、`application.html.erb`に記述して全ページで統一した方が良いと思ったのですがどうでしょう？
> `application.html.erb`で書くつもりだったので、管理者側では個別のページにはヘッダーとタイトルの間にマージンを設定していません。

わかりました。ユーザー側もそちらに合わせたいと思います

2021-05-21 00:53 UTC, snaruse389 approved these changes
確認しました

2021-05-21 00:53 UTC, merged