issue#58 エラーメッセージの日本語化
EC-site-TeamSmile/nagano_cake pull request #65
Opened 2021-05-21 09:16 UTC by haaanyan

#58

2021-05-21 10:47 UTC, Seiryu-alt requested changes
1点だけ修正お願いします！

2021-05-21 10:47 UTC, Seiryu-alt commented on app/views/shared/_form_error.html.erb
> +      <%= pluralize(model.errors.count, "件") %> 修正して下さい:
`pluralize`は"error"を個数に合わせて単数・複数形にするメソッドですので、日本語にするのでしたら以下で問題ありません
```suggestion
      <%= model.errors.count %>件 修正して下さい:
```

2021-05-21 14:38 UTC, snaruse389 requested changes
追加の方よろしくお願いします。

2021-05-21 14:38 UTC, snaruse389 commented on config/locales/models/ja.yml
> +        address_name: 宛名
モデルのGenre,Product,Orderのカラムもお願いします。

2021-05-23 01:57 UTC, snaruse389 approved these changes
確認しました

2021-05-23 01:58 UTC, Seiryu-alt approved these changes
OKです！

2021-05-23 01:58 UTC, merged