[fix] マイページと退会確認ページのレイアウトを微調整しました
EC-site-TeamSmile/nagano_cake pull request #70
Opened 2021-05-21 12:45 UTC by Seiryu-alt

2021-05-21 13:48 UTC, snaruse389 requested changes
どうでしょうか？

2021-05-21 13:48 UTC, snaruse389 commented on app/views/public/customers/show.html.erb
> +        <%= link_to "一覧を見る", orders_path, class:"btn btn-primary" %>
```suggestion
        <h5>登録情報</h5>
      </div>
      <div class="col-6 col-sm-4 col-md-3">
        <%= link_to "編集する", edit_customers_path, class:"btn btn-success btn-block" %>
      </div>
    </div>

    <div class="row mb-3">
      <div class="col-6 col-sm-4 col-md-3 d-flex align-items-center">
        <h5>配送先</h5>
      </div>
      <div class="col-6 col-sm-4 col-md-3">
        <%= link_to "一覧を見る", addresses_path, class:"btn btn-primary btn-block" %>
      </div>
    </div>

    <div class="row">
      <div class="col-6 col-sm-4 col-md-3 d-flex align-items-center">
        <h5>注文履歴</h5>
      </div>
      <div class="col-6 col-sm-4 col-md-3">
        <%= link_to "一覧を見る", orders_path, class:"btn btn-primary btn-block" %>
```

ボタンの横幅が揃えることができ、見た目がよくなると思います。

2021-05-22 00:13 UTC, Seiryu-alt commented on app/views/public/customers/show.html.erb
> +        <%= link_to "一覧を見る", orders_path, class:"btn btn-primary" %>
変更しました！

2021-05-22 13:59 UTC, hikaru-webcamp approved these changes

2021-05-23 01:03 UTC, snaruse389 approved these changes
確認しました。

2021-05-23 01:04 UTC, merged